site_name: Siddhi-IO-FILE
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi IO File: index.md
- About:
  - License: about/license.md
- API Docs:
  - 1.0.0-M2-SNAPSHOT: api/1.0.0-M2-SNAPSHOT.md
  - 1.0.0-M1-SNAPSHOT: api/1.0.0-M1-SNAPSHOT.md
theme: material
