site_name: Siddhi-IO-File
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi IO File: index.md
- API Docs:
  - 1.0.0-M4-SNAPSHOT: api/1.0.0-M4-SNAPSHOT.md
  - 1.0.0-M5-SNAPSHOT: api/1.0.0-M5-SNAPSHOT.md
  - 1.0.0-M6-SNAPSHOT: api/1.0.0-M6-SNAPSHOT.md
  - 1.0.0-M7-SNAPSHOT: api/1.0.0-M7-SNAPSHOT.md
- License: about/license.md
theme: material
